"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('is_hs', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_basic_industry'), 'stock_basic', ['industry'], unique=False)
    op.create_index(op.f('ix_stock_basic_market'), 'stock_basic', ['market'], unique=False)
    op.create_index(op.f('ix_stock_basic_name'), 'stock_basic', ['name'], unique=False)
    op.create_index(op.f('ix_stock_basic_symbol'), 'stock_basic', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_basic_ts_code'), 'stock_basic', ['ts_code'], unique=True)
    
    op.create_table('daily_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('pre_close', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('change', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('pct_chg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('vol', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quote_trade_date'), 'daily_quote', ['trade_date'], unique=False)
    op.create_index(op.f('ix_daily_quote_ts_code'), 'daily_quote', ['ts_code'], unique=False)
    op.create_index('ix_daily_quote_ts_code_trade_date', 'daily_quote', ['ts_code', 'trade_date'], unique=True)
    
    op.create_table('technical_indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ma5', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ma10', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ma20', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ma60', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ema12', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ema26', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('macd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('rsi', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('kdj_k', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('kdj_d', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('kdj_j', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('boll_upper', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('boll_mid', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('boll_lower', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('volume_ma5', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('volume_ma10', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_indicator_trade_date'), 'technical_indicator', ['trade_date'], unique=False)
    op.create_index(op.f('ix_technical_indicator_ts_code'), 'technical_indicator', ['ts_code'], unique=False)
    op.create_index('ix_technical_indicator_ts_code_trade_date', 'technical_indicator', ['ts_code', 'trade_date'], unique=True)
    
    op.create_table('nine_turn_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('td_setup', sa.Integer(), nullable=True),
    sa.Column('td_countdown', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=10), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nine_turn_signal_signal_type'), 'nine_turn_signal', ['signal_type'], unique=False)
    op.create_index(op.f('ix_nine_turn_signal_trade_date'), 'nine_turn_signal', ['trade_date'], unique=False)
    op.create_index(op.f('ix_nine_turn_signal_ts_code'), 'nine_turn_signal', ['ts_code'], unique=False)
    op.create_index('ix_nine_turn_signal_ts_code_trade_date', 'nine_turn_signal', ['ts_code', 'trade_date'], unique=True)
    
    op.create_table('data_update_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_update_log_status'), 'data_update_log', ['status'], unique=False)
    op.create_index(op.f('ix_data_update_log_task_name'), 'data_update_log', ['task_name'], unique=False)
    op.create_index(op.f('ix_data_update_log_task_type'), 'data_update_log', ['task_type'], unique=False)
    
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_data_update_log_task_type'), table_name='data_update_log')
    op.drop_index(op.f('ix_data_update_log_task_name'), table_name='data_update_log')
    op.drop_index(op.f('ix_data_update_log_status'), table_name='data_update_log')
    op.drop_table('data_update_log')
    op.drop_index('ix_nine_turn_signal_ts_code_trade_date', table_name='nine_turn_signal')
    op.drop_index(op.f('ix_nine_turn_signal_ts_code'), table_name='nine_turn_signal')
    op.drop_index(op.f('ix_nine_turn_signal_trade_date'), table_name='nine_turn_signal')
    op.drop_index(op.f('ix_nine_turn_signal_signal_type'), table_name='nine_turn_signal')
    op.drop_table('nine_turn_signal')
    op.drop_index('ix_technical_indicator_ts_code_trade_date', table_name='technical_indicator')
    op.drop_index(op.f('ix_technical_indicator_ts_code'), table_name='technical_indicator')
    op.drop_index(op.f('ix_technical_indicator_trade_date'), table_name='technical_indicator')
    op.drop_table('technical_indicator')
    op.drop_index('ix_daily_quote_ts_code_trade_date', table_name='daily_quote')
    op.drop_index(op.f('ix_daily_quote_ts_code'), table_name='daily_quote')
    op.drop_index(op.f('ix_daily_quote_trade_date'), table_name='daily_quote')
    op.drop_table('daily_quote')
    op.drop_index(op.f('ix_stock_basic_ts_code'), table_name='stock_basic')
    op.drop_index(op.f('ix_stock_basic_symbol'), table_name='stock_basic')
    op.drop_index(op.f('ix_stock_basic_name'), table_name='stock_basic')
    op.drop_index(op.f('ix_stock_basic_market'), table_name='stock_basic')
    op.drop_index(op.f('ix_stock_basic_industry'), table_name='stock_basic')
    op.drop_table('stock_basic')
    # ### end Alembic commands ###