"""Add missing exchange column

Revision ID: 52c3719b7c63
Revises: 0001
Create Date: 2025-07-23 15:12:57.847247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52c3719b7c63'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nine_turn_signal_signal_type'), table_name='nine_turn_signal')
    op.drop_index(op.f('ix_nine_turn_signal_trade_date'), table_name='nine_turn_signal')
    op.drop_index(op.f('ix_nine_turn_signal_ts_code'), table_name='nine_turn_signal')
    op.drop_index(op.f('ix_nine_turn_signal_ts_code_trade_date'), table_name='nine_turn_signal')
    op.drop_table('nine_turn_signal')
    op.drop_index(op.f('ix_technical_indicator_trade_date'), table_name='technical_indicator')
    op.drop_index(op.f('ix_technical_indicator_ts_code'), table_name='technical_indicator')
    op.drop_index(op.f('ix_technical_indicator_ts_code_trade_date'), table_name='technical_indicator')
    op.drop_table('technical_indicator')
    op.drop_index(op.f('ix_daily_quote_trade_date'), table_name='daily_quote')
    op.drop_index(op.f('ix_daily_quote_ts_code'), table_name='daily_quote')
    op.drop_index(op.f('ix_daily_quote_ts_code_trade_date'), table_name='daily_quote')
    op.drop_table('daily_quote')
    op.drop_index(op.f('ix_data_update_log_status'), table_name='data_update_log')
    op.drop_index(op.f('ix_data_update_log_task_name'), table_name='data_update_log')
    op.drop_index(op.f('ix_data_update_log_task_type'), table_name='data_update_log')
    op.drop_table('data_update_log')
    op.add_column('stock_basic', sa.Column('exchange', sa.String(length=10), nullable=False, comment='交易所代码'))
    op.add_column('stock_basic', sa.Column('curr_type', sa.String(length=10), nullable=True, comment='交易货币'))
    op.add_column('stock_basic', sa.Column('list_status', sa.String(length=1), nullable=False, comment='上市状态'))
    op.add_column('stock_basic', sa.Column('delist_date', sa.Date(), nullable=True, comment='退市日期'))
    op.alter_column('stock_basic', 'id',
               existing_type=sa.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('stock_basic_id_seq'::regclass)"))
    op.alter_column('stock_basic', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment='TS代码',
               existing_nullable=False)
    op.alter_column('stock_basic', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment='股票代码',
               existing_nullable=False)
    op.alter_column('stock_basic', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='股票名称',
               existing_nullable=False)
    op.alter_column('stock_basic', 'area',
               existing_type=sa.VARCHAR(length=20),
               comment='地域',
               existing_nullable=True)
    op.alter_column('stock_basic', 'industry',
               existing_type=sa.VARCHAR(length=50),
               comment='所属行业',
               existing_nullable=True)
    op.alter_column('stock_basic', 'market',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               comment='市场类型')
    op.alter_column('stock_basic', 'list_date',
               existing_type=sa.DATE(),
               comment='上市日期',
               existing_nullable=True)
    op.alter_column('stock_basic', 'is_hs',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=1),
               nullable=False,
               comment='是否沪深港通标的')
    op.alter_column('stock_basic', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='创建时间')
    op.alter_column('stock_basic', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='更新时间')
    op.drop_index(op.f('ix_stock_basic_industry'), table_name='stock_basic')
    op.drop_index(op.f('ix_stock_basic_market'), table_name='stock_basic')
    op.drop_index(op.f('ix_stock_basic_name'), table_name='stock_basic')
    op.create_index('idx_stock_basic_industry', 'stock_basic', ['industry'], unique=False)
    op.create_index('idx_stock_basic_list_status', 'stock_basic', ['list_status'], unique=False)
    op.create_index('idx_stock_basic_name', 'stock_basic', ['name'], unique=False)
    op.create_index('idx_stock_basic_symbol', 'stock_basic', ['symbol'], unique=False)
    op.add_column('system_config', sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'))
    op.add_column('system_config', sa.Column('config_value', sa.Text(), nullable=False, comment='配置值'))
    op.add_column('system_config', sa.Column('config_type', sa.String(length=20), nullable=False, comment='配置类型'))
    op.alter_column('system_config', 'id',
               existing_type=sa.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('system_config', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment='描述',
               existing_nullable=True)
    op.alter_column('system_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='是否启用')
    op.alter_column('system_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='创建时间')
    op.alter_column('system_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='更新时间')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.create_index('idx_system_config_active', 'system_config', ['is_active'], unique=False)
    op.create_index('idx_system_config_key', 'system_config', ['config_key'], unique=False)
    op.create_unique_constraint(None, 'system_config', ['config_key'])
    op.drop_column('system_config', 'value')
    op.drop_column('system_config', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('system_config', sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'system_config', type_='unique')
    op.drop_index('idx_system_config_key', table_name='system_config')
    op.drop_index('idx_system_config_active', table_name='system_config')
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.alter_column('system_config', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='更新时间')
    op.alter_column('system_config', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
    op.alter_column('system_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='是否启用')
    op.alter_column('system_config', 'description',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('system_config', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('system_config', 'config_type')
    op.drop_column('system_config', 'config_value')
    op.drop_column('system_config', 'config_key')
    op.drop_index('idx_stock_basic_symbol', table_name='stock_basic')
    op.drop_index('idx_stock_basic_name', table_name='stock_basic')
    op.drop_index('idx_stock_basic_list_status', table_name='stock_basic')
    op.drop_index('idx_stock_basic_industry', table_name='stock_basic')
    op.create_index(op.f('ix_stock_basic_name'), 'stock_basic', ['name'], unique=False)
    op.create_index(op.f('ix_stock_basic_market'), 'stock_basic', ['market'], unique=False)
    op.create_index(op.f('ix_stock_basic_industry'), 'stock_basic', ['industry'], unique=False)
    op.alter_column('stock_basic', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='更新时间')
    op.alter_column('stock_basic', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
    op.alter_column('stock_basic', 'is_hs',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=2),
               nullable=True,
               comment=None,
               existing_comment='是否沪深港通标的')
    op.alter_column('stock_basic', 'list_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='上市日期',
               existing_nullable=True)
    op.alter_column('stock_basic', 'market',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               comment=None,
               existing_comment='市场类型')
    op.alter_column('stock_basic', 'industry',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='所属行业',
               existing_nullable=True)
    op.alter_column('stock_basic', 'area',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='地域',
               existing_nullable=True)
    op.alter_column('stock_basic', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='股票名称',
               existing_nullable=False)
    op.alter_column('stock_basic', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='股票代码',
               existing_nullable=False)
    op.alter_column('stock_basic', 'ts_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='TS代码',
               existing_nullable=False)
    op.alter_column('stock_basic', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('stock_basic_id_seq'::regclass)"))
    op.drop_column('stock_basic', 'delist_date')
    op.drop_column('stock_basic', 'list_status')
    op.drop_column('stock_basic', 'curr_type')
    op.drop_column('stock_basic', 'exchange')
    op.create_table('data_update_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('records_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_update_log_pkey'))
    )
    op.create_index(op.f('ix_data_update_log_task_type'), 'data_update_log', ['task_type'], unique=False)
    op.create_index(op.f('ix_data_update_log_task_name'), 'data_update_log', ['task_name'], unique=False)
    op.create_index(op.f('ix_data_update_log_status'), 'data_update_log', ['status'], unique=False)
    op.create_table('daily_quote',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('high', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('low', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('close', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('pre_close', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('change', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('pct_chg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('vol', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=3), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_quote_pkey'))
    )
    op.create_index(op.f('ix_daily_quote_ts_code_trade_date'), 'daily_quote', ['ts_code', 'trade_date'], unique=True)
    op.create_index(op.f('ix_daily_quote_ts_code'), 'daily_quote', ['ts_code'], unique=False)
    op.create_index(op.f('ix_daily_quote_trade_date'), 'daily_quote', ['trade_date'], unique=False)
    op.create_table('technical_indicator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ma5', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('ma10', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('ma20', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('ma60', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('ema12', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('ema26', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('macd', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('macd_signal', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('macd_hist', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('rsi', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('kdj_k', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('kdj_d', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('kdj_j', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('boll_upper', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('boll_mid', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('boll_lower', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True),
    sa.Column('volume_ma5', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('volume_ma10', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('technical_indicator_pkey'))
    )
    op.create_index(op.f('ix_technical_indicator_ts_code_trade_date'), 'technical_indicator', ['ts_code', 'trade_date'], unique=True)
    op.create_index(op.f('ix_technical_indicator_ts_code'), 'technical_indicator', ['ts_code'], unique=False)
    op.create_index(op.f('ix_technical_indicator_trade_date'), 'technical_indicator', ['trade_date'], unique=False)
    op.create_table('nine_turn_signal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('td_setup', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('td_countdown', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signal_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('signal_strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nine_turn_signal_pkey'))
    )
    op.create_index(op.f('ix_nine_turn_signal_ts_code_trade_date'), 'nine_turn_signal', ['ts_code', 'trade_date'], unique=True)
    op.create_index(op.f('ix_nine_turn_signal_ts_code'), 'nine_turn_signal', ['ts_code'], unique=False)
    op.create_index(op.f('ix_nine_turn_signal_trade_date'), 'nine_turn_signal', ['trade_date'], unique=False)
    op.create_index(op.f('ix_nine_turn_signal_signal_type'), 'nine_turn_signal', ['signal_type'], unique=False)
    # ### end Alembic commands ###